version: 2.1

jobs:
    install:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ .Branch }}-{{ checksum "package-json.lock" }}
            - run: bun install --frozen-lockfile
            - save_cache:
                  key: nm-{{ .Branch }}-{{ checksum "package-json.lock" }}
                  paths:
                      - node_modules

    test_cover:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ .Branch }}-{{ checksum "bun.lock" }}
            - run: npm run test

    lint:
        docker:
            - image:cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ .Branch }}-{{ checksum "bun.lock" }}
            - run: npm run lint

workflows:
    version: 2
    build_and_publish:
        jobs:
            - install:
                  context: la_build_vars

            - test:
                  context: la_build_vars
                  requires:
                      - install

            - lint:
                  requires:
                      - install
