version: 2.1

jobs:
    install:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ checksum "package-lock.json" }}
            - run: npm ci
            - save_cache:
                  key: nm-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules

    test:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ checksum "package-lock.json" }}
            - run: npm run test

    lint:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ checksum "package-lock.json" }}
            - run: npm run lint

    publish:
        docker:
            - image: cimg/node:lts
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - nm-{{ checksum "package-lock.json" }}
            - run:
                name: Publish
                command: |
                    npm version "$CIRCLE_TAG"
                    npm run build
                    npm publish

workflows:
    version: 2
    build_and_publish:
        jobs:
            - install:
                  context: la_build_vars

            - test:
                  context: la_build_vars
                  requires:
                      - install

            - lint:
                  requires:
                      - install

            - publish:
                requires:
                    - install
                    - test
                    - lint
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.+/
